apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mssql.name" . }}-haproxy-config
  labels:
  {{- include "haproxy.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
  {{- include "haproxy.config" . | nindent 4 }}
