apiVersion: v1
kind: Service
metadata:
  name: ms16
  labels:
    mssql: ms16
spec:
  ports:
    - port: 1433
      name: mssql
  {{/*clusterIP: None*/}}
  publishNotReadyAddresses: true
  selector:
    mssql: ms16
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mssql.name" . }}-16
  labels:
    mssql: ms16
  {{- include "mssql.labels" . | nindent 4 }}
spec:
  serviceName: ms16
  replicas: 1
  selector:
    matchLabels:
      mssql: ms16
    {{- include "mssql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        mssql: ms16
      {{- include "mssql.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
      setHostnameAsFQDN: true
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
      - name: ms16
        imagePullPolicy: {{ .Values.pullPolicy }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              key: ACCEPT_EULA
              name: {{ include "mssql.fullname" . }}-sql-env
        - name: MSSQL_PID
          valueFrom:
            configMapKeyRef:
              key: MSSQL_PID
              name: {{ include "mssql.fullname" . }}-sql-env
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MSSQL_SA_PASSWORD
              name: {{ include "mssql.fullname" . }}-sql-env
        image: {{ .Values.ms16.image.repository }}:{{ .Values.ms16.image.tag | default
          .Chart.AppVersion }}
        ports:
        - containerPort: 1433
          protocol: TCP
        resources: {{- toYaml .Values.ms16.resources | nindent 10 }}
        volumeMounts:
          - mountPath: /scripts
            name: menagerie
      hostname: ms16
      volumes:
        - configMap:
            name: menagerie
          name: menagerie
