apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: {{ include "mssql.fullname" . }}-sa-password
    labels:
    {{- include "mssql.labels" . | nindent 4 }}
spec:
    refreshInterval: {{ .Values.externalSecret.refreshInterval }}
    secretStoreRef:
        name: eks-secret-store
        kind: SecretStore
    target:
        name: externalsecret
    data:
    {{- toYaml .Values.envSecrets | nindent 8 }}
