---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: zoo-mssql
build: {}
deploy:
  helm:
    releases:
      - name: zoo-db
        chartPath: ./haproxy
        version: 0.1.0
        upgradeOnChange: true
      - name: zoo-mssql
        chartPath: ./mssql
        version: 0.1.0
        upgradeOnChange: true
      - name: zoo-oracle
        chartPath: ./oracle
        version: 0.1.0
        upgradeOnChange: true

