---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: zoo-mssql
build:
  tagPolicy:
    envTemplate:
      template: "latest"
  artifacts:
    - image: registry.jetbrains.team/p/datagrip/containers/mssql-custom-14

      context: ./Docker/Microsoft
      docker:
        dockerfile: "Ms-14.dockerfile"
    - image: registry.jetbrains.team/p/datagrip/containers/mssql-custom-15

      context: ./Docker/Microsoft
      docker:
        dockerfile: "Ms-15.dockerfile"
    - image: registry.jetbrains.team/p/datagrip/containers/mssql-custom-16

      context: ./Docker/Microsoft
      docker:
        dockerfile: "Ms-16.dockerfile"
  local:
    useDockerCLI: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: zoo-mssql
        chartPath: ./mssql
        version: 0.1.0
        upgradeOnChange: true
        #setValueTemplates:
        #  ms14.image.tag: "{{.IMAGE_TAG}}"
        #  ms15.image.tag: "{{.IMAGE_TAG}}"
        #  ms16.image.tag: "{{.IMAGE_TAG}}"
        #  haproxy.image.tag: "{{.IMAGE_TAG}}"
