oracle11s:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/oracle-custom
    tag: 11.2.0.2-noncdb
  resources:
    limits:
      cpu: 1
      memory: "2Gi"
      ephemeral-storage: "5Gi"
    requests:
      cpu: "100m"
      memory: "500Mi"
      ephemeral-storage: "1Gi"
oracle12s:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/oracle-custom
    tag: 12.2.0.2-noncdb
  resources:
    limits:
      cpu: 1
      memory: "5Gi"
      ephemeral-storage: "5Gi"
    requests:
      cpu: "200m"
      memory: "500Mi"
      ephemeral-storage: "1Gi"
oracle12m:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/oracle-custom
    tag: 12.2.0.2-multi
  resources:
    limits:
      cpu: 2
      memory: "5Gi"
      ephemeral-storage: "5Gi"
    requests:
      cpu: "200m"
      memory: "500Mi"
      ephemeral-storage: "1Gi"
oracle19s:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/oracle-custom
    tag: 19.3-noncdb
  resources:
    limits:
      cpu: 1
      memory: "7Gi"
      ephemeral-storage: "5Gi"
    requests:
      cpu: "200m"
      memory: "500Mi"
      ephemeral-storage: "1Gi"
oracle19m:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/oracle-custom
    tag: 19.3-multi
  resources:
    limits:
      cpu: 1
      memory: "6Gi"
      ephemeral-storage: "5Gi"
    requests:
      cpu: "200m"
      memory: "500Mi"
      ephemeral-storage: "1Gi"
oracle21m:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/oracle-custom
    tag: 21.3-multi
  resources:
    limits:
      cpu: 1
      memory: "4Gi"
      ephemeral-storage: "5Gi"
    requests:
      cpu: "200m"
      memory: "500Mi"
      ephemeral-storage: "1Gi"
oracle23m:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/oracle-custom
    tag: 23.26-multi
  resources:
    limits:
      cpu: 1
      memory: "4Gi"
      ephemeral-storage: "5Gi"
    requests:
      cpu: "200m"
      memory: "500Mi"
      ephemeral-storage: "1Gi"

replicas: 1

pullPolicy: Always

# Directory the setup scripts are mounted into
scriptsMountPath:
  # 11.2.0.2
  oracle11s: "/scripts"
  # 12.2 / 19.3 / 21.3 / 23.26
  default: "/opt/oracle/scripts/setup"

#sqlEnv: {}

externalSecret:
  refreshInterval: 1h

envSecrets:
  - secretKey: password
    remoteRef:
      key: Kubernetes/zoodb/Oracle
      property: password


imagePullSecrets:
  - name: space-registry-datagrip
