apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: {{ include "oracle.fullname" . }}-sys-password
    labels:
    {{- include "oracle.labels" . | nindent 8 }}
spec:
    refreshInterval: {{ .Values.externalSecret.refreshInterval }}
    secretStoreRef:
        name: eks-secret-store
        kind: SecretStore
    target:
        name: {{ include "oracle.fullname" . }}-sys-password
    data:
    {{- toYaml .Values.envSecrets | nindent 8 }}
