ms14:
  image:
    repository:  registry.jetbrains.team/p/datagrip/containers/mssql-custom
    tag: 14
  resources:
    limits:
      memory: "4Gi"
    requests:
      memory: "250Mi"
ms15:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/mssql-custom
    tag: 15
  resources:
    limits:
      memory: "4Gi"
    requests:
      memory: "250Mi"
ms16:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/mssql-custom
    tag: 16
  resources:
    limits:
      memory: "4Gi"
    requests:
      memory: "250Mi"

replicas: 1

pullPolicy: Always

sqlEnv:
  acceptEula: "Y"
  mssqlPid: Developer

externalSecret:
  refreshInterval: 1h


envSecrets:
  - secretKey: password
    remoteRef:
      key: Kubernetes/zoodb/MSSQL
      property: password

imagePullSecrets:
  - name: space-registry-datagrip
