ms14:
  image:
    repository:  registry.jetbrains.team/p/datagrip/containers/mssql-custom-14
    tag: latest
  resources:
    limits:
      memory: "4Gi"
    requests:
      memory: "250Mi"
ms15:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/mssql-custom-15
    tag: latest
  resources:
    limits:
      memory: "4Gi"
    requests:
      memory: "250Mi"
ms16:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/mssql-custom-16
    tag: latest
  resources:
    limits:
      memory: "4Gi"
    requests:
      memory: "250Mi"

replicas: 1

pullPolicy: Always

sqlEnv:
  acceptEula: "Y"
  mssqlPid: Developer
  mssqlSaPassword: Mini-pass


imagePullSecrets:
  - name: space-registry-datagrip
