haproxy:
  image:
    repository: registry.jetbrains.team/p/datagrip/containers/haproxy
    tag: "3.3.4"
  resources:
    limits:
      memory: "500Mi"
    requests:
      memory: "100Mi"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: datagripdb.labs.jb.gg
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-target-node-labels: "node-type=shared"
    service.beta.kubernetes.io/aws-load-balancer-name: k8s-datagripdb-nlb-1
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.connection_termination.enabled=true,preserve_client_ip.enabled=false
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"  # min=2

servicePorts:
  - name: "ms14"
    port: 25140
    targetPort: 14334
  - name: "ms15"
    port: 25150
    targetPort: 14335
  - name: "ms16"
    port: 25160
    targetPort: 14336
  - name: "ora11s"
    port: 25110
    targetPort: 15210
  - name: "ora12s"
    port: 25111
    targetPort: 15211
  - name: "ora12m"
    port: 25112
    targetPort: 15212
  - name: "ora19s"
    port: 25113
    targetPort: 15213
  - name: "ora19m"
    port: 25114
    targetPort: 15214
  - name: "ora21m"
    port: 25115
    targetPort: 15215
  - name: "ora23m"
    port: 25116
    targetPort: 15216

replicas: 1
type: LoadBalancer
pullPolicy: Always

timeouts:
  connect: 5s
  client: 60s
  server: 60s

tcpServices:
  - name: ms14
    frontendPort: 14334
    backend:
      servers:
        - name: ms14
          host: ms14
          port: 1433
  - name: ms15
    frontendPort: 14335
    backend:
      servers:
        - name: ms15
          host: ms15
          port: 1433
  - name: ms16
    frontendPort: 14336
    backend:
      servers:
        - name: ms16
          host: ms16
          port: 1433
  - name: ora11s
    frontendPort: 15210
    backend:
      servers:
        - name: ora11s
          host: ora11s
          port: 1521
  - name: ora12s
    frontendPort: 15211
    backend:
      servers:
        - name: ora12s
          host: ora12s
          port: 1521
  - name: ora12m
    frontendPort: 15212
    backend:
      servers:
        - name: ora12m
          host: ora12m
          port: 1521
  - name: ora19s
    frontendPort: 15213
    backend:
      servers:
        - name: ora19s
          host: ora19s
          port: 1521
  - name: ora19m
    frontendPort: 15214
    backend:
      servers:
        - name: ora19m
          host: ora19m
          port: 1521
  - name: ora21m
    frontendPort: 15215
    backend:
      servers:
        - name: ora21s
          host: ora21s
          port: 1521
  - name: ora23m
    frontendPort: 15216
    backend:
      servers:
        - name: ora23s
          host: ora23s
          port: 1521

imagePullSecrets:
  - name: space-registry-datagrip
